version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        ENV: development
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - ENV=development

  backend-prod:
    build:
      context: ./backend
      args:
        ENV: production
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - ENV=production

  frontend:
    build:
      context: ./CV
    volumes:
      - ./CV:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
